/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import datos.Prueba;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import negocio.nPrueba;
import sun.awt.image.ByteArrayImageSource;
import sun.awt.image.ToolkitImage;

/**
 *
 * @author Billy
 */
public class FrmVerPruebas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmVerPruebas
     */
    private int codigoalerta;
    
    private nPrueba pruebas;
    
    private byte[] logo;
    
    private int idprueba;
    
    
    private Prueba datoprueba;
    
    
    
    public FrmVerPruebas() {
        initComponents();
        iniciar();
    }
    
    public void iniciar(){
        this.setSize(566,374);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelimagen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Pruebas de Bullying");

        jPanel1.setPreferredSize(new java.awt.Dimension(550, 250));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelimagen, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelimagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/next.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/prev.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconos/ubica.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(84, 84, 84))))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int self =jTable1.getSelectedRow();
        int nrof = self;
        int idimagen=Integer.parseInt(String.valueOf(jTable1.getValueAt(nrof,0)));
        

        Image logoObtenido=new ToolkitImage(new ByteArrayImageSource(pruebas.devolversimbolo(idimagen))); //obtengo el logo
        ImageIcon imagen = new ImageIcon(logoObtenido);   //le paso el logo a un tipo imagen icono
        Icon iconoaMostrar = new ImageIcon(imagen.getImage().getScaledInstance(405,240, logoObtenido.SCALE_DEFAULT));
        labelimagen.setIcon(iconoaMostrar);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cargartablapruebas(codigoalerta);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        sliderfotonext();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        sliderfotoprev();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelimagen;
    // End of variables declaration//GEN-END:variables

    /**
     * @param codigoalerta the codigoalerta to set
     */
    public void setCodigoalerta(int codigoalerta) {
        this.codigoalerta = codigoalerta;
    }
    
    
    public void cargartablapruebas(int codaler){
        pruebas = new nPrueba();
        jTable1.setModel(pruebas.Listar(codaler));
    }
    
    
    public void sliderfotonext(){
        int self =jTable1.getSelectedRow()+1;
        int nrof = self;
        int idimagen=Integer.parseInt(String.valueOf(jTable1.getValueAt(nrof,0)));
        

        Image logoObtenido=new ToolkitImage(new ByteArrayImageSource(pruebas.devolversimbolo(idimagen))); //obtengo el logo
        ImageIcon imagen = new ImageIcon(logoObtenido);   //le paso el logo a un tipo imagen icono
        Icon iconoaMostrar = new ImageIcon(imagen.getImage().getScaledInstance(405,240, logoObtenido.SCALE_DEFAULT));
        labelimagen.setIcon(iconoaMostrar);
    }
    
    public void sliderfotoprev(){
        int self =jTable1.getSelectedRow()-1;
        int nrof = self;
        int idimagen=Integer.parseInt(String.valueOf(jTable1.getValueAt(nrof,0)));
        

        Image logoObtenido=new ToolkitImage(new ByteArrayImageSource(pruebas.devolversimbolo(idimagen))); //obtengo el logo
        ImageIcon imagen = new ImageIcon(logoObtenido);   //le paso el logo a un tipo imagen icono
        Icon iconoaMostrar = new ImageIcon(imagen.getImage().getScaledInstance(405,240, logoObtenido.SCALE_DEFAULT));
        labelimagen.setIcon(iconoaMostrar);
    }
    
    
//     public byte[] imagenaByte(String ruta){
//   
//       File f = new File(ruta);
//       InputStream is = null; 
//        try {
//            is = new FileInputStream(f);
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(FrmVerPruebas.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//      byte[] buffer = new byte[(int) f.length()];
//        try {
//            int readers = is.read(buffer);
//        } catch (IOException ex) {
//            Logger.getLogger(FrmVerPruebas.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    
//        return buffer;
//    }
     
//     
//     public void byteaimagen(){
//         
//         datoprueba = new Prueba();
//         datoprueba.ListarLogo(1);
//         
//         
//        Image logoObtenido=new ToolkitImage(new ByteArrayImageSource(datoprueba.getImagen())); //obtengo el logo
//        ImageIcon imagen = new ImageIcon(logoObtenido);   //le paso el logo a un tipo imagen icono
//        Icon iconoaMostrar = new ImageIcon(imagen.getImage().getScaledInstance(165,165, logoObtenido.SCALE_DEFAULT));
//        labelimagen.setIcon(iconoaMostrar);
//     }
   
     

    
    
    
    
    
    
}
