package datos;
// Generated 06-dic-2013 15:07:58 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Criteria;
import org.hibernate.Session;

/**
 * Alerta generated by hbm2java
 */
public class Alerta  implements java.io.Serializable {


     private Integer alertaId;
     private Estudiante estudianteByVictimaId;
     private Estudiante estudianteByAgresorId;
     private String descripcion;
     private Set pruebas = new HashSet(0);

    public Alerta() {
    }
    
    public Alerta(int idalert) {
        this.alertaId = idalert;
    }

	
    public Alerta(Estudiante estudianteByVictimaId, Estudiante estudianteByAgresorId, String descripcion) {
        this.estudianteByVictimaId = estudianteByVictimaId;
        this.estudianteByAgresorId = estudianteByAgresorId;
        this.descripcion = descripcion;
    }
    public Alerta(Estudiante estudianteByVictimaId, Estudiante estudianteByAgresorId, String descripcion, Set pruebas) {
       this.estudianteByVictimaId = estudianteByVictimaId;
       this.estudianteByAgresorId = estudianteByAgresorId;
       this.descripcion = descripcion;
       this.pruebas = pruebas;
    }
   
    public Integer getAlertaId() {
        return this.alertaId;
    }
    
    public void setAlertaId(Integer alertaId) {
        this.alertaId = alertaId;
    }
    public Estudiante getEstudianteByVictimaId() {
        return this.estudianteByVictimaId;
    }
    
    public void setEstudianteByVictimaId(Estudiante estudianteByVictimaId) {
        this.estudianteByVictimaId = estudianteByVictimaId;
    }
    public Estudiante getEstudianteByAgresorId() {
        return this.estudianteByAgresorId;
    }
    
    public void setEstudianteByAgresorId(Estudiante estudianteByAgresorId) {
        this.estudianteByAgresorId = estudianteByAgresorId;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPruebas() {
        return this.pruebas;
    }
    
    public void setPruebas(Set pruebas) {
        this.pruebas = pruebas;
    }

    public List Listar() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Criteria criteria = session.createCriteria(this.getClass());
        List list = criteria.list();
        return list;
    }

    @Override
    public String toString() {
        return this.alertaId+","+this.descripcion+","+this.estudianteByVictimaId.getNombreCompleto()+","+this.estudianteByAgresorId.getNombreCompleto();
    }
    
    


}


