package datos;
// Generated 06-dic-2013 15:07:58 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Criteria;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {

     private Integer cursoId;
     private Unidadeducativa unidadeducativa;
     private String nivel;
     private int grado;
     private Set paralelos = new HashSet(0);

    public Curso() {
    }

     public Curso(int codcurso) {
        this.cursoId = codcurso;
    }
     
      public Curso(Unidadeducativa unidadeducativa) {
        this.unidadeducativa = unidadeducativa;
    }
	
    public Curso(Unidadeducativa unidadeducativa, String nivel, int grado) {
        this.unidadeducativa = unidadeducativa;
        this.nivel = nivel;
        this.grado = grado;
    }
    
    public Curso(Unidadeducativa unidadeducativa, String nivel, int grado, Set paralelos) {
       this.unidadeducativa = unidadeducativa;
       this.nivel = nivel;
       this.grado = grado;
       this.paralelos = paralelos;
    }
   
    public Integer getCursoId() {
        return this.cursoId;
    }
    
    public void setCursoId(Integer cursoId) {
        this.cursoId = cursoId;
    }
    public Unidadeducativa getUnidadeducativa() {
        return this.unidadeducativa;
    }
    
    public void setUnidadeducativa(Unidadeducativa unidadeducativa) {
        this.unidadeducativa = unidadeducativa;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public int getGrado() {
        return this.grado;
    }
    
    public void setGrado(int grado) {
        this.grado = grado;
    }
    public Set getParalelos() {
        return this.paralelos;
    }
    
    public void setParalelos(Set paralelos) {
        this.paralelos = paralelos;
    }

    public List Listar() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Criteria criteria = session.createCriteria(this.getClass());
        List list = criteria.list();
        return list;
    }
   
    
    public static Object buscar(String clase, String atributo, Object valor, boolean usarComillas) throws Exception {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction transaction = session.beginTransaction();

        if (usarComillas) {
            valor = "'" + valor + "'";
        }
        Query query = session.createQuery("FROM " + clase + " AS C WHERE C." + atributo + " = " + valor);
        Object object = query.uniqueResult();
        session.close();
        return object;
    }

}


