package datos;
// Generated 06-dic-2013 15:07:58 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Director generated by hbm2java
 */
public class Director  implements java.io.Serializable {


     private Integer directorId;
     private String nombreCompleto;
     private String correo;
     private int telefono;
     private Set unidadeducativas = new HashSet(0);

    public Director() {
    }

	
    public Director(String nombreCompleto, String correo, int telefono) {
        this.nombreCompleto = nombreCompleto;
        this.correo = correo;
        this.telefono = telefono;
    }
    public Director(String nombreCompleto, String correo, int telefono, Set unidadeducativas) {
       this.nombreCompleto = nombreCompleto;
       this.correo = correo;
       this.telefono = telefono;
       this.unidadeducativas = unidadeducativas;
    }
   
    public Integer getDirectorId() {
        return this.directorId;
    }
    
    public void setDirectorId(Integer directorId) {
        this.directorId = directorId;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public Set getUnidadeducativas() {
        return this.unidadeducativas;
    }
    
    public void setUnidadeducativas(Set unidadeducativas) {
        this.unidadeducativas = unidadeducativas;
    }

    
     public void Insertar() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction transaction = session.beginTransaction();
        try {
            session.persist(this);
            transaction.commit();
        } catch (Exception e) {
            transaction.rollback();
        } finally {
            session.close();
        }
    }


//    public static void main(String[] args) {
//        // TODO code application logic here
//        Director obj = new Director("Aquilino suntura","Asuntura@gmail.com",79852369);
//        obj.Insertar();
//    } 
     
     
}


