package datos;
// Generated 06-dic-2013 15:07:58 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Criteria;
import org.hibernate.Session;

/**
 * Paralelo generated by hbm2java
 */
public class Paralelo  implements java.io.Serializable {


     private Integer paraleloId;
     private Curso curso;
     private String nombre;
     private Set estudiantes = new HashSet(0);

    public Paralelo() {
    }

	
    public Paralelo(Curso curso, String nombre) {
        this.curso = curso;
        this.nombre = nombre;
    }
    
    
    public Paralelo(Curso curso) {
        this.curso = curso;
    }
    
    public Paralelo(Curso curso, String nombre, Set estudiantes) {
       this.curso = curso;
       this.nombre = nombre;
       this.estudiantes = estudiantes;
    }
   
    public Integer getParaleloId() {
        return this.paraleloId;
    }
    
    public void setParaleloId(Integer paraleloId) {
        this.paraleloId = paraleloId;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }

     public List Listar() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Criteria criteria = session.createCriteria(this.getClass());
        List list = criteria.list();
        return list;
    }



}


